/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDataTable: typeof import('./src/components/AppDataTable.vue')['default']
    AttachmentUploader: typeof import('./src/components/AttachmentUploader.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    BudgetUtilizationWidget: typeof import('./src/components/dashboard/BudgetUtilizationWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    DetailHeader: typeof import('./src/components/DetailHeader.vue')['default']
    DocTypeFormFields: typeof import('./src/components/doc-config/DocTypeFormFields.vue')['default']
    DonutChart: typeof import('./src/components/charts/DonutChart.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    EventTimeline: typeof import('./src/components/EventTimeline.vue')['default']
    FormDatePicker: typeof import('./src/components/FormDatePicker.vue')['default']
    FormPreview: typeof import('./src/components/doc-config/FormPreview.vue')['default']
    FormStepper: typeof import('./src/components/FormStepper.vue')['default']
    ImageCropper: typeof import('./src/components/ImageCropper.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MyDocumentsWidget: typeof import('./src/components/dashboard/MyDocumentsWidget.vue')['default']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageToolbar: typeof import('./src/components/PageToolbar.vue')['default']
    ParetoChart: typeof import('./src/components/charts/ParetoChart.vue')['default']
    PaymentSlips: typeof import('./src/components/payments/PaymentSlips.vue')['default']
    PendingApprovalsWidget: typeof import('./src/components/dashboard/PendingApprovalsWidget.vue')['default']
    ProfileImagePanel: typeof import('./src/components/ProfileImagePanel.vue')['default']
    RecordSettlementDialog: typeof import('./src/components/settlements/RecordSettlementDialog.vue')['default']
    RefChainEditor: typeof import('./src/components/doc-config/RefChainEditor.vue')['default']
    ReportCard: typeof import('./src/components/reports/ReportCard.vue')['default']
    ReviewApprovalDialog: typeof import('./src/components/documents/ReviewApprovalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SettlementPanel: typeof import('./src/components/settlements/SettlementPanel.vue')['default']
    SignaturePanel: typeof import('./src/components/SignaturePanel.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    StatTiles: typeof import('./src/components/reports/StatTiles.vue')['default']
    TableSkeleton: typeof import('./src/components/TableSkeleton.vue')['default']
    ThemedIllustration: typeof import('./src/components/ThemedIllustration.vue')['default']
    UnreadNotificationsWidget: typeof import('./src/components/dashboard/UnreadNotificationsWidget.vue')['default']
    VendorBankAccountsPanel: typeof import('./src/components/master-data/VendorBankAccountsPanel.vue')['default']
    WhatsAppSpeedDial: typeof import('./src/components/WhatsAppSpeedDial.vue')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
