import { Migration } from '@mikro-orm/migrations';

/**
 * Initial schema for the Multi-Company ERP — all 37 tables from
 * erp_approval_system.dbml. Generated from the MikroORM entity metadata.
 */
export class Migration20260617000000 extends Migration {
  override async up(): Promise<void> {
    this.addSql(`create table "app_user" ("id" uuid not null, "username" varchar(255) not null, "email" varchar(255) not null, "password_hash" varchar(255) null, "status" varchar(255) not null default 'ACTIVE', "created_at" timestamptz null, constraint "app_user_pkey" primary key ("id"));`);
    this.addSql(`alter table "app_user" add constraint "app_user_username_unique" unique ("username");`);
    this.addSql(`alter table "app_user" add constraint "app_user_email_unique" unique ("email");`);
    this.addSql(`create table "currency" ("code" varchar(3) not null, "name" varchar(255) not null, "symbol" varchar(255) null, "decimal_places" int not null default 2, "is_active" boolean not null default true, constraint "currency_pkey" primary key ("code"));`);
    this.addSql(`create table "company" ("id" uuid not null, "code" varchar(255) not null, "name_th" varchar(255) not null, "name_en" varchar(255) null, "tax_id" varchar(13) not null, "branch_code" varchar(5) not null default '00000', "base_currency" varchar(3) null, "is_active" boolean not null default true, "created_at" timestamptz null, constraint "company_pkey" primary key ("id"));`);
    this.addSql(`alter table "company" add constraint "company_code_unique" unique ("code");`);
    this.addSql(`create table "department" ("id" uuid not null, "company_id" uuid not null, "dept_code" varchar(255) not null, "name" varchar(255) not null, "parent_dept_id" uuid null, "cost_center" varchar(255) null, "is_active" boolean not null default true, constraint "department_pkey" primary key ("id"));`);
    this.addSql(`alter table "department" add constraint "department_company_id_dept_code_unique" unique ("company_id", "dept_code");`);
    this.addSql(`create table "document_type" ("id" uuid not null, "code" varchar(255) not null, "name" varchar(255) not null, "category" text check ("category" in ('PROCUREMENT', 'FINANCE', 'HR', 'ADMIN', 'IT')) not null, "requires_budget" boolean not null default false, "requires_quota" boolean not null default false, "post_action" varchar(255) null, "is_active" boolean not null default true, constraint "document_type_pkey" primary key ("id"));`);
    this.addSql(`alter table "document_type" add constraint "document_type_code_unique" unique ("code");`);
    this.addSql(`create table "doc_running_number" ("id" uuid not null, "company_id" uuid not null, "document_type_id" uuid not null, "year" int not null, "prefix" varchar(255) null, "current_no" int not null default 0, constraint "doc_running_number_pkey" primary key ("id"));`);
    this.addSql(`alter table "doc_running_number" add constraint "doc_running_number_company_id_document_type_id_year_unique" unique ("company_id", "document_type_id", "year");`);
    this.addSql(`create table "approval_delegation" ("id" uuid not null, "company_id" uuid not null, "delegator_id" uuid not null, "delegate_id" uuid not null, "document_type_id" uuid null, "amount_limit" numeric(15,2) null, "start_date" date not null, "end_date" date not null, "reason" varchar(255) null, "status" varchar(255) not null default 'ACTIVE', "created_at" timestamptz null, constraint "approval_delegation_pkey" primary key ("id"));`);
    this.addSql(`create index "approval_delegation_company_id_delegate_id_index" on "approval_delegation" ("company_id", "delegate_id");`);
    this.addSql(`create index "approval_delegation_delegator_id_status_index" on "approval_delegation" ("delegator_id", "status");`);
    this.addSql(`create table "employee" ("id" uuid not null, "company_id" uuid not null, "department_id" uuid not null, "user_id" uuid null, "emp_code" varchar(255) not null, "full_name" varchar(255) not null, "position" varchar(255) null, "job_level" varchar(255) null, "salary" numeric(15,2) null, "hire_date" date null, "status" varchar(255) not null default 'ACTIVE', constraint "employee_pkey" primary key ("id"));`);
    this.addSql(`alter table "employee" add constraint "employee_user_id_unique" unique ("user_id");`);
    this.addSql(`alter table "employee" add constraint "employee_company_id_emp_code_unique" unique ("company_id", "emp_code");`);
    this.addSql(`create table "exchange_rate" ("id" uuid not null, "company_id" uuid null, "from_currency" varchar(3) not null, "to_currency" varchar(3) not null, "rate" numeric(18,8) not null, "rate_date" date not null, "rate_type" varchar(255) not null default 'DAILY', "source" varchar(255) null, "created_by" uuid null, "created_at" timestamptz null, constraint "exchange_rate_pkey" primary key ("id"));`);
    this.addSql(`alter table "exchange_rate" add constraint "exchange_rate_company_id_from_currency_to_currenc_77451_unique" unique ("company_id", "from_currency", "to_currency", "rate_date", "rate_type");`);
    this.addSql(`create table "fiscal_year" ("id" uuid not null, "company_id" uuid not null, "year" int not null, "start_date" date not null, "end_date" date not null, "status" varchar(255) not null default 'OPEN', constraint "fiscal_year_pkey" primary key ("id"));`);
    this.addSql(`alter table "fiscal_year" add constraint "fiscal_year_company_id_year_unique" unique ("company_id", "year");`);
    this.addSql(`create table "budget" ("id" uuid not null, "fiscal_year_id" uuid not null, "department_id" uuid not null, "gl_account" varchar(255) not null, "budget_name" varchar(255) null, "amount_total" numeric(15,2) not null, "control_policy" text check ("control_policy" in ('HARD_STOP', 'SOFT_WARNING')) not null default 'HARD_STOP', "status" varchar(255) not null default 'ACTIVE', constraint "budget_pkey" primary key ("id"));`);
    this.addSql(`alter table "budget" add constraint "budget_fiscal_year_id_department_id_gl_account_unique" unique ("fiscal_year_id", "department_id", "gl_account");`);
    this.addSql(`create table "form_template" ("id" uuid not null, "document_type_id" uuid not null, "version" int not null default 1, "status" varchar(255) not null default 'DRAFT', "created_at" timestamptz null, constraint "form_template_pkey" primary key ("id"));`);
    this.addSql(`alter table "form_template" add constraint "form_template_document_type_id_version_unique" unique ("document_type_id", "version");`);
    this.addSql(`create table "form_field" ("id" uuid not null, "form_template_id" uuid not null, "field_name" varchar(255) not null, "field_label" varchar(255) not null, "field_type" varchar(255) not null, "is_required" boolean not null default false, "sort_order" int not null default 0, "options_json" text null, "condition_json" text null, constraint "form_field_pkey" primary key ("id"));`);
    this.addSql(`create table "holiday_calendar" ("id" uuid not null, "company_id" uuid not null, "holiday_date" date not null, "name" varchar(255) not null, constraint "holiday_calendar_pkey" primary key ("id"));`);
    this.addSql(`alter table "holiday_calendar" add constraint "holiday_calendar_company_id_holiday_date_unique" unique ("company_id", "holiday_date");`);
    this.addSql(`create table "item" ("id" uuid not null, "item_code" varchar(255) not null, "name" varchar(255) not null, "category" varchar(255) null, "default_unit" varchar(255) null, "default_gl_account" varchar(255) null, "is_active" boolean not null default true, constraint "item_pkey" primary key ("id"));`);
    this.addSql(`alter table "item" add constraint "item_item_code_unique" unique ("item_code");`);
    this.addSql(`create table "item_company" ("id" uuid not null, "item_id" uuid not null, "company_id" uuid not null, "is_active" boolean not null default true, constraint "item_company_pkey" primary key ("id"));`);
    this.addSql(`alter table "item_company" add constraint "item_company_item_id_company_id_unique" unique ("item_id", "company_id");`);
    this.addSql(`create table "notification_template" ("id" uuid not null, "code" varchar(255) not null, "channel" varchar(255) not null, "subject_template" varchar(255) null, "body_template" text null, "is_active" boolean not null default true, constraint "notification_template_pkey" primary key ("id"));`);
    this.addSql(`alter table "notification_template" add constraint "notification_template_code_unique" unique ("code");`);
    this.addSql(`create table "permission" ("id" uuid not null, "code" varchar(255) not null, "name" varchar(255) not null, "module" varchar(255) not null, "is_active" boolean not null default true, constraint "permission_pkey" primary key ("id"));`);
    this.addSql(`alter table "permission" add constraint "permission_code_unique" unique ("code");`);
    this.addSql(`create table "quota" ("id" uuid not null, "company_id" uuid not null, "department_id" uuid null, "quota_type" varchar(255) not null, "unit" varchar(255) not null, "limit_value" numeric(15,2) not null, "reset_cycle" varchar(255) not null default 'YEARLY', "is_active" boolean not null default true, constraint "quota_pkey" primary key ("id"));`);
    this.addSql(`create table "quota_entitlement" ("id" uuid not null, "quota_id" uuid not null, "employee_id" uuid not null, "year" int not null, "entitled_value" numeric(15,2) not null, "carried_over" numeric(15,2) not null default 0, "adjusted" numeric(15,2) not null default 0, constraint "quota_entitlement_pkey" primary key ("id"));`);
    this.addSql(`alter table "quota_entitlement" add constraint "quota_entitlement_quota_id_employee_id_year_unique" unique ("quota_id", "employee_id", "year");`);
    this.addSql(`create table "role" ("id" uuid not null, "company_id" uuid not null, "code" varchar(255) not null, "name" varchar(255) not null, "description" varchar(255) null, "is_active" boolean not null default true, constraint "role_pkey" primary key ("id"));`);
    this.addSql(`alter table "role" add constraint "role_company_id_code_unique" unique ("company_id", "code");`);
    this.addSql(`create table "role_permission" ("id" uuid not null, "role_id" uuid not null, "permission_id" uuid not null, "scope" text check ("scope" in ('OWN', 'DEPARTMENT', 'COMPANY', 'GROUP')) not null default 'DEPARTMENT', constraint "role_permission_pkey" primary key ("id"));`);
    this.addSql(`alter table "role_permission" add constraint "role_permission_role_id_permission_id_unique" unique ("role_id", "permission_id");`);
    this.addSql(`create table "user_company_role" ("id" uuid not null, "user_id" uuid not null, "company_id" uuid not null, "department_id" uuid not null, "role_id" uuid not null, "is_default" boolean not null default false, "valid_from" date null, "valid_to" date null, constraint "user_company_role_pkey" primary key ("id"));`);
    this.addSql(`create index "user_company_role_user_id_index" on "user_company_role" ("user_id");`);
    this.addSql(`alter table "user_company_role" add constraint "user_company_role_user_id_company_id_role_id_unique" unique ("user_id", "company_id", "role_id");`);
    this.addSql(`create table "vendor" ("id" uuid not null, "vendor_code" varchar(255) not null, "name" varchar(255) not null, "tax_id" varchar(13) null, "address" varchar(255) null, "contact_name" varchar(255) null, "contact_phone" varchar(255) null, "payment_term_days" int not null default 30, "is_active" boolean not null default true, constraint "vendor_pkey" primary key ("id"));`);
    this.addSql(`alter table "vendor" add constraint "vendor_vendor_code_unique" unique ("vendor_code");`);
    this.addSql(`create table "vendor_company" ("id" uuid not null, "vendor_id" uuid not null, "company_id" uuid not null, "is_active" boolean not null default true, "approved_date" date null, constraint "vendor_company_pkey" primary key ("id"));`);
    this.addSql(`alter table "vendor_company" add constraint "vendor_company_vendor_id_company_id_unique" unique ("vendor_id", "company_id");`);
    this.addSql(`create table "workflow" ("id" uuid not null, "company_id" uuid not null, "name" varchar(255) not null, "condition_json" text null, "is_active" boolean not null default true, constraint "workflow_pkey" primary key ("id"));`);
    this.addSql(`create table "document" ("id" uuid not null, "doc_no" varchar(255) not null, "company_id" uuid not null, "department_id" uuid not null, "document_type_id" uuid not null, "form_template_id" uuid not null, "workflow_id" uuid not null, "current_step_no" int not null default 0, "created_by" uuid not null, "ref_document_id" uuid null, "related_employee_id" uuid null, "vendor_id" uuid null, "currency" varchar(3) null, "exchange_rate" numeric(18,8) not null default 1, "total_amount" numeric(15,2) null, "base_total_amount" numeric(15,2) null, "status" text check ("status" in ('DRAFT', 'SUBMITTED', 'IN_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')) not null default 'DRAFT', "submitted_at" timestamptz null, "approved_at" timestamptz null, "created_at" timestamptz null, constraint "document_pkey" primary key ("id"));`);
    this.addSql(`create index "document_created_by_index" on "document" ("created_by");`);
    this.addSql(`create index "document_company_id_department_id_status_index" on "document" ("company_id", "department_id", "status");`);
    this.addSql(`alter table "document" add constraint "document_company_id_doc_no_unique" unique ("company_id", "doc_no");`);
    this.addSql(`create table "quota_usage" ("id" uuid not null, "quota_id" uuid not null, "document_id" uuid not null, "employee_id" uuid null, "qty_used" numeric(15,2) not null, "usage_type" varchar(255) not null default 'USE', "created_at" timestamptz null, constraint "quota_usage_pkey" primary key ("id"));`);
    this.addSql(`create index "quota_usage_quota_id_index" on "quota_usage" ("quota_id");`);
    this.addSql(`create index "quota_usage_document_id_index" on "quota_usage" ("document_id");`);
    this.addSql(`create table "notification" ("id" uuid not null, "company_id" uuid not null, "user_id" uuid not null, "template_id" uuid null, "document_id" uuid null, "channel" varchar(255) not null, "title" varchar(255) null, "message" text null, "status" varchar(255) not null default 'PENDING', "is_read" boolean not null default false, "read_at" timestamptz null, "sent_at" timestamptz null, "created_at" timestamptz null, constraint "notification_pkey" primary key ("id"));`);
    this.addSql(`create index "notification_document_id_index" on "notification" ("document_id");`);
    this.addSql(`create index "notification_user_id_is_read_index" on "notification" ("user_id", "is_read");`);
    this.addSql(`create table "document_line" ("id" uuid not null, "document_id" uuid not null, "line_no" int not null, "item_id" uuid null, "description" varchar(255) not null, "qty" numeric(15,4) not null default 1, "unit" varchar(255) null, "unit_price" numeric(15,2) not null default 0, "line_amount" numeric(15,2) not null, "base_line_amount" numeric(15,2) null, "budget_id" uuid null, "gl_account" varchar(255) null, "received_qty" numeric(15,4) not null default 0, "line_status" varchar(255) not null default 'OPEN', constraint "document_line_pkey" primary key ("id"));`);
    this.addSql(`create index "document_line_budget_id_index" on "document_line" ("budget_id");`);
    this.addSql(`alter table "document_line" add constraint "document_line_document_id_line_no_unique" unique ("document_id", "line_no");`);
    this.addSql(`create table "document_attachment" ("id" uuid not null, "document_id" uuid not null, "file_name" varchar(255) not null, "file_path" varchar(255) not null, "file_size_kb" int null, "mime_type" varchar(255) null, "uploaded_by" uuid not null, "uploaded_at" timestamptz null, constraint "document_attachment_pkey" primary key ("id"));`);
    this.addSql(`create index "document_attachment_document_id_index" on "document_attachment" ("document_id");`);
    this.addSql(`create table "doc_field_value" ("id" uuid not null, "document_id" uuid not null, "form_field_id" uuid not null, "field_value" text null, constraint "doc_field_value_pkey" primary key ("id"));`);
    this.addSql(`alter table "doc_field_value" add constraint "doc_field_value_document_id_form_field_id_unique" unique ("document_id", "form_field_id");`);
    this.addSql(`create table "budget_txn" ("id" uuid not null, "budget_id" uuid not null, "document_id" uuid not null, "txn_type" text check ("txn_type" in ('RESERVE', 'ACTUAL', 'RELEASE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUST_INCREASE', 'ADJUST_DECREASE')) not null, "amount" numeric(15,2) not null, "remark" varchar(255) null, "created_by" uuid null, "created_at" timestamptz null, constraint "budget_txn_pkey" primary key ("id"));`);
    this.addSql(`create index "budget_txn_budget_id_index" on "budget_txn" ("budget_id");`);
    this.addSql(`create index "budget_txn_document_id_index" on "budget_txn" ("document_id");`);
    this.addSql(`create table "budget_movement" ("id" uuid not null, "company_id" uuid not null, "document_id" uuid not null, "movement_type" varchar(255) not null, "from_budget_id" uuid null, "to_budget_id" uuid null, "amount" numeric(15,2) not null, "reason" varchar(255) null, "effective_date" date null, "created_at" timestamptz null, constraint "budget_movement_pkey" primary key ("id"));`);
    this.addSql(`create index "budget_movement_document_id_index" on "budget_movement" ("document_id");`);
    this.addSql(`create index "budget_movement_from_budget_id_index" on "budget_movement" ("from_budget_id");`);
    this.addSql(`create index "budget_movement_to_budget_id_index" on "budget_movement" ("to_budget_id");`);
    this.addSql(`create table "approval_log" ("id" uuid not null, "document_id" uuid not null, "step_no" int not null, "approver_id" uuid not null, "delegated_from" uuid null, "action" text check ("action" in ('APPROVE', 'REJECT', 'RETURN', 'DELEGATE')) not null, "remark" text null, "acted_at" timestamptz null, constraint "approval_log_pkey" primary key ("id"));`);
    this.addSql(`create index "approval_log_document_id_index" on "approval_log" ("document_id");`);
    this.addSql(`create table "dept_doc_type" ("id" uuid not null, "department_id" uuid not null, "document_type_id" uuid not null, "form_template_id" uuid not null, "workflow_id" uuid not null, "is_active" boolean not null default true, constraint "dept_doc_type_pkey" primary key ("id"));`);
    this.addSql(`alter table "dept_doc_type" add constraint "dept_doc_type_department_id_document_type_id_unique" unique ("department_id", "document_type_id");`);
    this.addSql(`create table "workflow_step" ("id" uuid not null, "workflow_id" uuid not null, "step_no" int not null, "step_name" varchar(255) null, "approver_role_id" uuid null, "approver_user_id" uuid null, "amount_min" numeric(15,2) null, "amount_max" numeric(15,2) null, "approve_mode" varchar(255) not null default 'SEQUENTIAL', "sla_hours" int null, constraint "workflow_step_pkey" primary key ("id"));`);
    this.addSql(`alter table "workflow_step" add constraint "workflow_step_workflow_id_step_no_unique" unique ("workflow_id", "step_no");`);
    this.addSql(`alter table "company" add constraint "company_base_currency_foreign" foreign key ("base_currency") references "currency" ("code") on update cascade on delete set null;`);
    this.addSql(`alter table "department" add constraint "department_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "department" add constraint "department_parent_dept_id_foreign" foreign key ("parent_dept_id") references "department" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "doc_running_number" add constraint "doc_running_number_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "doc_running_number" add constraint "doc_running_number_document_type_id_foreign" foreign key ("document_type_id") references "document_type" ("id") on update cascade;`);
    this.addSql(`alter table "approval_delegation" add constraint "approval_delegation_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "approval_delegation" add constraint "approval_delegation_delegator_id_foreign" foreign key ("delegator_id") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "approval_delegation" add constraint "approval_delegation_delegate_id_foreign" foreign key ("delegate_id") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "approval_delegation" add constraint "approval_delegation_document_type_id_foreign" foreign key ("document_type_id") references "document_type" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "employee" add constraint "employee_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "employee" add constraint "employee_department_id_foreign" foreign key ("department_id") references "department" ("id") on update cascade;`);
    this.addSql(`alter table "employee" add constraint "employee_user_id_foreign" foreign key ("user_id") references "app_user" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "exchange_rate" add constraint "exchange_rate_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "exchange_rate" add constraint "exchange_rate_from_currency_foreign" foreign key ("from_currency") references "currency" ("code") on update cascade;`);
    this.addSql(`alter table "exchange_rate" add constraint "exchange_rate_to_currency_foreign" foreign key ("to_currency") references "currency" ("code") on update cascade;`);
    this.addSql(`alter table "exchange_rate" add constraint "exchange_rate_created_by_foreign" foreign key ("created_by") references "app_user" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "fiscal_year" add constraint "fiscal_year_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "budget" add constraint "budget_fiscal_year_id_foreign" foreign key ("fiscal_year_id") references "fiscal_year" ("id") on update cascade;`);
    this.addSql(`alter table "budget" add constraint "budget_department_id_foreign" foreign key ("department_id") references "department" ("id") on update cascade;`);
    this.addSql(`alter table "form_template" add constraint "form_template_document_type_id_foreign" foreign key ("document_type_id") references "document_type" ("id") on update cascade;`);
    this.addSql(`alter table "form_field" add constraint "form_field_form_template_id_foreign" foreign key ("form_template_id") references "form_template" ("id") on update cascade;`);
    this.addSql(`alter table "holiday_calendar" add constraint "holiday_calendar_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "item_company" add constraint "item_company_item_id_foreign" foreign key ("item_id") references "item" ("id") on update cascade;`);
    this.addSql(`alter table "item_company" add constraint "item_company_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "quota" add constraint "quota_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "quota" add constraint "quota_department_id_foreign" foreign key ("department_id") references "department" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "quota_entitlement" add constraint "quota_entitlement_quota_id_foreign" foreign key ("quota_id") references "quota" ("id") on update cascade;`);
    this.addSql(`alter table "quota_entitlement" add constraint "quota_entitlement_employee_id_foreign" foreign key ("employee_id") references "employee" ("id") on update cascade;`);
    this.addSql(`alter table "role" add constraint "role_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "role_permission" add constraint "role_permission_role_id_foreign" foreign key ("role_id") references "role" ("id") on update cascade;`);
    this.addSql(`alter table "role_permission" add constraint "role_permission_permission_id_foreign" foreign key ("permission_id") references "permission" ("id") on update cascade;`);
    this.addSql(`alter table "user_company_role" add constraint "user_company_role_user_id_foreign" foreign key ("user_id") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "user_company_role" add constraint "user_company_role_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "user_company_role" add constraint "user_company_role_department_id_foreign" foreign key ("department_id") references "department" ("id") on update cascade;`);
    this.addSql(`alter table "user_company_role" add constraint "user_company_role_role_id_foreign" foreign key ("role_id") references "role" ("id") on update cascade;`);
    this.addSql(`alter table "vendor_company" add constraint "vendor_company_vendor_id_foreign" foreign key ("vendor_id") references "vendor" ("id") on update cascade;`);
    this.addSql(`alter table "vendor_company" add constraint "vendor_company_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "workflow" add constraint "workflow_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_department_id_foreign" foreign key ("department_id") references "department" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_document_type_id_foreign" foreign key ("document_type_id") references "document_type" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_form_template_id_foreign" foreign key ("form_template_id") references "form_template" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_workflow_id_foreign" foreign key ("workflow_id") references "workflow" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_created_by_foreign" foreign key ("created_by") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "document" add constraint "document_ref_document_id_foreign" foreign key ("ref_document_id") references "document" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "document" add constraint "document_related_employee_id_foreign" foreign key ("related_employee_id") references "employee" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "document" add constraint "document_vendor_id_foreign" foreign key ("vendor_id") references "vendor" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "document" add constraint "document_currency_foreign" foreign key ("currency") references "currency" ("code") on update cascade on delete set null;`);
    this.addSql(`alter table "quota_usage" add constraint "quota_usage_quota_id_foreign" foreign key ("quota_id") references "quota" ("id") on update cascade;`);
    this.addSql(`alter table "quota_usage" add constraint "quota_usage_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "quota_usage" add constraint "quota_usage_employee_id_foreign" foreign key ("employee_id") references "employee" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "notification" add constraint "notification_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "notification" add constraint "notification_user_id_foreign" foreign key ("user_id") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "notification" add constraint "notification_template_id_foreign" foreign key ("template_id") references "notification_template" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "notification" add constraint "notification_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "document_line" add constraint "document_line_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "document_line" add constraint "document_line_item_id_foreign" foreign key ("item_id") references "item" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "document_line" add constraint "document_line_budget_id_foreign" foreign key ("budget_id") references "budget" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "document_attachment" add constraint "document_attachment_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "document_attachment" add constraint "document_attachment_uploaded_by_foreign" foreign key ("uploaded_by") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "doc_field_value" add constraint "doc_field_value_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "doc_field_value" add constraint "doc_field_value_form_field_id_foreign" foreign key ("form_field_id") references "form_field" ("id") on update cascade;`);
    this.addSql(`alter table "budget_txn" add constraint "budget_txn_budget_id_foreign" foreign key ("budget_id") references "budget" ("id") on update cascade;`);
    this.addSql(`alter table "budget_txn" add constraint "budget_txn_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "budget_txn" add constraint "budget_txn_created_by_foreign" foreign key ("created_by") references "app_user" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "budget_movement" add constraint "budget_movement_company_id_foreign" foreign key ("company_id") references "company" ("id") on update cascade;`);
    this.addSql(`alter table "budget_movement" add constraint "budget_movement_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "budget_movement" add constraint "budget_movement_from_budget_id_foreign" foreign key ("from_budget_id") references "budget" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "budget_movement" add constraint "budget_movement_to_budget_id_foreign" foreign key ("to_budget_id") references "budget" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "approval_log" add constraint "approval_log_document_id_foreign" foreign key ("document_id") references "document" ("id") on update cascade;`);
    this.addSql(`alter table "approval_log" add constraint "approval_log_approver_id_foreign" foreign key ("approver_id") references "app_user" ("id") on update cascade;`);
    this.addSql(`alter table "approval_log" add constraint "approval_log_delegated_from_foreign" foreign key ("delegated_from") references "app_user" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "dept_doc_type" add constraint "dept_doc_type_department_id_foreign" foreign key ("department_id") references "department" ("id") on update cascade;`);
    this.addSql(`alter table "dept_doc_type" add constraint "dept_doc_type_document_type_id_foreign" foreign key ("document_type_id") references "document_type" ("id") on update cascade;`);
    this.addSql(`alter table "dept_doc_type" add constraint "dept_doc_type_form_template_id_foreign" foreign key ("form_template_id") references "form_template" ("id") on update cascade;`);
    this.addSql(`alter table "dept_doc_type" add constraint "dept_doc_type_workflow_id_foreign" foreign key ("workflow_id") references "workflow" ("id") on update cascade;`);
    this.addSql(`alter table "workflow_step" add constraint "workflow_step_workflow_id_foreign" foreign key ("workflow_id") references "workflow" ("id") on update cascade;`);
    this.addSql(`alter table "workflow_step" add constraint "workflow_step_approver_role_id_foreign" foreign key ("approver_role_id") references "role" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "workflow_step" add constraint "workflow_step_approver_user_id_foreign" foreign key ("approver_user_id") references "app_user" ("id") on update cascade on delete set null;`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "workflow_step" cascade;`);
    this.addSql(`drop table if exists "dept_doc_type" cascade;`);
    this.addSql(`drop table if exists "approval_log" cascade;`);
    this.addSql(`drop table if exists "budget_movement" cascade;`);
    this.addSql(`drop table if exists "budget_txn" cascade;`);
    this.addSql(`drop table if exists "doc_field_value" cascade;`);
    this.addSql(`drop table if exists "document_attachment" cascade;`);
    this.addSql(`drop table if exists "document_line" cascade;`);
    this.addSql(`drop table if exists "notification" cascade;`);
    this.addSql(`drop table if exists "quota_usage" cascade;`);
    this.addSql(`drop table if exists "document" cascade;`);
    this.addSql(`drop table if exists "workflow" cascade;`);
    this.addSql(`drop table if exists "vendor_company" cascade;`);
    this.addSql(`drop table if exists "vendor" cascade;`);
    this.addSql(`drop table if exists "user_company_role" cascade;`);
    this.addSql(`drop table if exists "role_permission" cascade;`);
    this.addSql(`drop table if exists "role" cascade;`);
    this.addSql(`drop table if exists "quota_entitlement" cascade;`);
    this.addSql(`drop table if exists "quota" cascade;`);
    this.addSql(`drop table if exists "permission" cascade;`);
    this.addSql(`drop table if exists "notification_template" cascade;`);
    this.addSql(`drop table if exists "item_company" cascade;`);
    this.addSql(`drop table if exists "item" cascade;`);
    this.addSql(`drop table if exists "holiday_calendar" cascade;`);
    this.addSql(`drop table if exists "form_field" cascade;`);
    this.addSql(`drop table if exists "form_template" cascade;`);
    this.addSql(`drop table if exists "budget" cascade;`);
    this.addSql(`drop table if exists "fiscal_year" cascade;`);
    this.addSql(`drop table if exists "exchange_rate" cascade;`);
    this.addSql(`drop table if exists "employee" cascade;`);
    this.addSql(`drop table if exists "approval_delegation" cascade;`);
    this.addSql(`drop table if exists "doc_running_number" cascade;`);
    this.addSql(`drop table if exists "document_type" cascade;`);
    this.addSql(`drop table if exists "department" cascade;`);
    this.addSql(`drop table if exists "company" cascade;`);
    this.addSql(`drop table if exists "currency" cascade;`);
    this.addSql(`drop table if exists "app_user" cascade;`);
  }
}
